service:
  description: Request body with the name of a service
  required: true
  content:
    application/json:
      schema:
        type: object
        required:
          - service
        properties:
          service:
            type: string
