plotter_config:
  type: object
  properties:
    delay:
      type: integer
      format: int32
    parallel:
      type: boolean
      default: false      
    number:
      type: integer
      format: int32
      default: 1      
    size:
      $ref: "./k_size.yaml#/k_size"
    queue:
      type: string
      default: "default"      
    temp_dir:
      type: string
    temp_dir2:
      type: string
    destination_dir:
      type: string
    buffer:
      type: integer
      format: int32
      default: 4608      
    buckets:
      type: integer
      format: int32
      default: 128      
    alt_fingerprint:
      type: integer
      format: uint32
      nullable: true
    pool_contract_address:
      type: string
    pool_public_key:
      type: string
    farmer_public_key:
      type: string
    memo:
      type: string
    no_bit_field:
      type: boolean
      default: false      
    num_threads:
      type: integer
      format: int32
      default: 2      
    exclude_final_dir:
      type: boolean
      default: false      
    override_k:
      type: boolean
      default: false
      nullable: true
