openapi: 3.0.3
info:
  description: "The Chia node and services come with a JSON RPC API server that allows you to access information and control the services. These are accessible via HTTP, WebSockets, or via client SDKs. The ports can be configured in ~/.chia/mainnet/config/config.yaml. The RPC ports should not be exposed to the internet. TLS certificates are used to secure the communication."
  version: 1.2.11
  title: Chia RPC
  termsOfService: https://www.chia.net/assets/legal/Guidelines-for-Using-Chia-Network.pdf
  contact:
    name: Chia Network
    url: https://www.chia.net/
    email: hello@chia.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: https://localhost:8559
    description: Farmer RPC
security:
  - bearerAuth: []
components:
  requestBodies:
    empty:
      $ref: "./requestBodies/empty.yaml#/empty"
  schemas:
    apiResponse:
      $ref: "./schemas/apiResponse.yaml#/apiResponse"
  securitySchemes:
    bearerAuth:
      $ref: "./securitySchemes/bearerAuth.yaml#/bearerAuth"
tags:
- name: Farmer
  description: The farmer RPC API is exposed, by default, on port 8559 and contains methods for managing the farmer.
paths:
  /get_reward_targets:
    post:
      tags:
      - Farmer
      summary: Get the farm and pool reward targets.
      description: Get the farm and pool reward targets.
      operationId: get_reward_targets
      requestBody:
        description: indicator of whether to include private keys in the search
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                search_for_private_key:
                  type: boolean                 
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - farmer_target
                  - pool_target
                properties:
                  farmer_target:
                    type: "string"
                  pool_target:
                    type: "string"
                  have_farmer_sk:
                    type: "boolean"
                  have_pool_sk:
                    type: "boolean"                    
                allOf:
                  - $ref: "#/components/schemas/apiResponse"                                      
externalDocs:
  description: Find out more about chia
  url: http://chia.net
