openapi: 3.0.3
info:
  description: "The Chia node and services come with a JSON RPC API server that allows you to access information and control the services. These are accessible via HTTP, WebSockets, or via client SDKs. The ports can be configured in ~/.chia/mainnet/config/config.yaml. The RPC ports should not be exposed to the internet. TLS certificates are used to secure the communication."
  version: 1.2.11
  title: Chia RPC
  termsOfService: https://www.chia.net/assets/legal/Guidelines-for-Using-Chia-Network.pdf
  contact:
    name: Chia Network
    url: https://www.chia.net/
    email: hello@chia.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: https://localhost:8560
    description: Harvester RPC
security:
  - bearerAuth: []
components:
  requestBodies:
    empty:
      $ref: "./requestBodies/empty.yaml#/empty"
  schemas:
    k_size:
      $ref: "./schemas/k_size.yaml#/k_size"  
    plot_info:
      $ref: "./schemas/plot_info.yaml#/plot_info"
    apiResponse:
      $ref: "./schemas/apiResponse.yaml#/apiResponse"
  securitySchemes:
    bearerAuth:
      $ref: "./securitySchemes/bearerAuth.yaml#/bearerAuth"
tags:
- name: Harvester
  description: The harvester RPC API is exposed, by default, on port 8560 and contains methods for managing plot files and directories.
paths:
  /add_plot_directory:
    post:
      tags:
      - Harvester
      summary: Add a plot directory to the harvester configuration.
      description: Add a plot directory to the harvester configuration.
      operationId: add_plot_directory
      requestBody:
        description: The directory name to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_id:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"
  /remove_plot_directory:
    post:
      tags:
      - Harvester
      summary: Removes a plot directory from the harveser configuration.
      description: Removes a plot directory from the harveser configuration.
      operationId: remove_plot_directory
      requestBody:
        description: The directory name to remove
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet_id:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"                
  /get_plot_directories:
    post:
      tags:
      - Harvester
      summary: Get the list of plot directories from the harvester configuration.
      description: Get the list of plot directories from the harvester configuration.
      operationId: get_plot_directories
      requestBody:
        $ref: "#/components/requestBodies/empty"      
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  directories:
                    type: array
                    items:
                      type: string 
                allOf:
                  - $ref: "#/components/schemas/apiResponse"
  /refresh_plots:
    post:
      tags:
      - Harvester
      summary: Refresh the list of plots.
      description: Refresh the list of plots.
      operationId: refresh_plots
      requestBody:
        $ref: "#/components/requestBodies/empty"      
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"                  
  /get_plots:
    post:
      tags:
      - Harvester
      summary: Get information about the plots the harvester knows about.
      description: Get information about the plots the harvester knows about.
      operationId: get_plots
      requestBody:
        $ref: "#/components/requestBodies/empty"      
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  failed_to_open_filenames:
                    type: array
                    items:
                      type: string
                  not_found_filenames:
                    type: array
                    items:
                      type: string
                  plots:
                    type: array
                    items:
                      $ref: "#/components/schemas/plot_info"                                 
                allOf:
                  - $ref: "#/components/schemas/apiResponse"
  /delete_plot:
    post:
      tags:
      - Harvester
      summary: Permanently delete a plot file.
      description: Permanently delete a plot file.
      operationId: delete_plot
      requestBody:
          required: true
          description: the file name of the plot
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
              example:
                filename: plot-k33-2021-06-12-03-55-1d5a2afe637578d6c9dfa04484854831012b678921a8dce5a8aee9c0fd3c1470.plot
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiResponse"
externalDocs:
  description: Find out more about chia
  url: http://chia.net
