openapi: 3.0.3
info:
  description: "The Chia node and services come with a JSON RPC API server that allows you to access information and control the services. These are accessible via HTTP, WebSockets, or via client SDKs. The ports can be configured in ~/.chia/mainnet/config/config.yaml. The RPC ports should not be exposed to the internet. TLS certificates are used to secure the communication."
  version: 1.2.11
  title: Chia RPC
  termsOfService: https://www.chia.net/assets/legal/Guidelines-for-Using-Chia-Network.pdf
  contact:
    name: Chia Network
    url: https://www.chia.net/
    email: hello@chia.net
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: https://localhost:9256
    description: Wallet RPC
security:
  - bearerAuth: []
components:
  requestBodies:
    empty:
      $ref: "./requestBodies/empty.yaml#/empty"
    wallet_id:
      $ref: "./requestBodies/wallet_id.yaml#/wallet_id"
  schemas:
    wallet_balance:
      $ref: "./schemas/wallet_balance.yaml#/wallet_balance"
    apiResponse:
      $ref: "./schemas/apiResponse.yaml#/apiResponse"
  securitySchemes:
    bearerAuth:
      $ref: "./securitySchemes/bearerAuth.yaml#/bearerAuth"
tags:
- name: Wallet
  description: The wallet RPC API is exposed, by default, on port 9256 and contains methods for managing wallet, trades, offers and transactions.
- name: Standard Wallet
  description: Methods for standard wallet operations.  
paths:
  /get_wallet_balance:
    post:
      tags:
      - Standard Wallet
      summary: Get the balance of a specific wallet (in units of mojos).
      description: Get the balance of a specific wallet (in units of mojos).
      operationId: get_wallet_balance
      requestBody:
        $ref: "#/components/requestBodies/wallet_id"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: 
                  - wallet_balance
                properties:
                  wallet_balance:
                    $ref: "#/components/schemas/wallet_balance"
                allOf:
                  - $ref: "#/components/schemas/apiResponse"
  /get_network_info:
    post:
      tags:
      - Wallet
      summary: Retrieves some information about the current network.
      operationId: wallet_get_network_info
      requestBody:
        $ref: "#/components/requestBodies/empty"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                required:
                  - network_name
                  - network_prefix                  
                properties:
                  network_name:
                    type: "string"
                  network_prefix:
                    type: "string" 
                allOf:
                  - $ref: "#/components/schemas/apiResponse"
externalDocs:
  description: Find out more about chia
  url: http://chia.net
